eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautltZone: http://localhost:8989/eureka

server:
  port: 8089
spring:
  application:
    name: Taches
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/taches_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: TAHAtaha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


