server:
  port: 8200

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      mvc:
        routes:
          - id: Projet
            uri: http://localhost:8087
            predicates:
              - Path=/Projets/**
          - id: Ressources
            uri: http://localhost:8090
            predicates:
              - Path=/Ressources/**
          - id: Taches
            uri: http://localhost:8089
            predicates:
              - Path=/Taches/**
          - id: Auth
            uri: http://localhost:8070
            predicates:
              - Path=/Auth/**